// Generated by CoffeeScript 1.7.1
var YAML;

if (typeof YAML === "undefined" || YAML === null) {
  YAML = require('../../src/Yaml');
}

describe('YAML Parser', function() {
  it('parses simple sequence', function() {
    return expect(YAML.parse('- apple\n- banana\n- carrot')).toEqual(['apple', 'banana', 'carrot']);
  });
  it('parses nested sequences', function() {
    return expect(YAML.parse('-\n - foo\n - bar\n - baz')).toEqual([['foo', 'bar', 'baz']]);
  });
  it('parses mixed sequences', function() {
    return expect(YAML.parse('- apple\n-\n - foo\n - bar\n - x123\n- banana\n- carrot')).toEqual(['apple', ['foo', 'bar', 'x123'], 'banana', 'carrot']);
  });
  it('parses deeply nested sequences', function() {
    return expect(YAML.parse('-\n -\n  - uno\n  - dos')).toEqual([[['uno', 'dos']]]);
  });
  it('parses simple mapping', function() {
    return expect(YAML.parse('foo: whatever\nbar: stuff')).toEqual({
      foo: 'whatever',
      bar: 'stuff'
    });
  });
  return it('parses sequence in a mapping', function() {
    return expect(YAML.parse('foo: whatever\nbar:\n - uno\n - dos')).toEqual({
      foo: 'whatever',
      bar: ['uno', 'dos']
    });
  });
});
